In [1]:
import pandas as pd

In [5]:
news = pd.read_csv('2025 news for formatting.csv',encoding='Latin')
news

,original sort,content,contains date,len,Type,Group ID
0,1,Kimani Vidal,#VALUE!,12.0,Player name,1
1,2,Kimani Vidal waived by Chargers,#VALUE!,31.0,Headline / Summary,1
2,3,"Tue, Aug 26th 10:12pm EDT",22,NaN,Date,1
3,4,Kimani Vidal has been waived by the Los Angele...,#VALUE!,91.0,Headline / Summary,1
4,5,Fantasy Impact: The Chargers released several ...,#VALUE!,NaN,Fantasy Impact,1
...,...,...,...,...,...,...
3058,3059,Darren Waller (return to football) on track to...,#VALUE!,58.0,Headline / Summary,513
3059,3060,"Mon, Sep 1st 12:04pm EDT",21,NaN,Date,513
3060,3061,Darren Waller is on track to play in Sunday's ...,#VALUE!,113.0,Headline / Summary,513
3061,3062,Fantasy Impact: Waller recently returned to pr...,#VALUE!,NaN,Fantasy Impact,513
3062,3063,Category: Injury Updates,#VALUE!,NaN,Category,513

In [14]:
players=[]
headlines=[]
dates=[]
fantasy_impacts=[]
categories=[]
player_news_groups = news['Group ID'].drop_duplicates().values

for g in player_news_groups:
    news_df = news[news['Group ID']==g]
    player = ''
    headline = ''
    date =''
    fantasy_impact = ''
    category = ''
    for index, row in news_df.iterrows():
        if row['Type'] == 'Player name':
            player = row['content']
        elif row['Type'] == 'Headline / Summary':
            if len(row['content']) > len(headline):
                headline = row['content']
        elif row['Type'] == 'Date':
            date = row['content']
        elif row['Type'] == 'Fantasy Impact':
            fantasy_impact = row['content']
        elif row['Type'] == 'Category':
            category = row['content']
    players.append(player)
    headlines.append(headline)
    dates.append(date)
    fantasy_impacts.append(fantasy_impact)
    categories.append(category)

formatted_news_df = pd.DataFrame()
formatted_news_df['player'] = players
formatted_news_df['date'] = dates
formatted_news_df['headline'] = headlines
formatted_news_df['fantasy_impact'] = fantasy_impacts
formatted_news_df['category'] = categories

formatted_news_df = formatted_news_df.drop_duplicates().reset_index(drop=True)
formatted_news_df

,player,date,headline,fantasy_impact,category
0,Kimani Vidal,"Tue, Aug 26th 10:12pm EDT",Kimani Vidal has been waived by the Los Angele...,Fantasy Impact: The Chargers released several ...,Category: Transactions
1,Nyheim Miller-Hines,"Tue, Aug 26th 10:10pm EDT",Nyheim Miller-Hines has been cut by the Los An...,"Fantasy Impact: To no surprise, Miller-Hines h...",Category: Transactions
2,Jalen Reagor,"Tue, Aug 26th 10:07pm EDT",Jalen Reagor has been released by the Los Ange...,Fantasy Impact: The Chargers made a number of ...,Category: Transactions
3,Taylor Heinicke,"Tue, Aug 26th 10:06pm EDT",Taylor Heinicke has been released by the Los A...,Fantasy Impact: The veteran quarterback did no...,Category: Transactions
4,Kaleb McGary,"Tue, Aug 26th 10:04pm EDT",Kaleb McGary (knee) will miss the entire seaso...,Fantasy Impact: The Falcons placed McGary on i...,Category: Injury Updates
...,...,...,...,...,...
475,Jauan Jennings,"Mon, Sep 1st 3:27pm EDT",Jauan Jennings was seen at practice on Monday....,Fantasy Impact: Jennings has been battling a c...,Category: Injury Updates
476,C.J. Gardner-Johnson,"Mon, Sep 1st 3:25pm EDT",Texans coach DeMeco Ryans said S C.J. Gardner-...,Fantasy Impact: Gardner-Johnson has been sidel...,Category: Injury Updates
477,Cade Otton,"Mon, Sep 1st 3:20pm EDT",Cade Otton practiced on Monday. (Source: Rick ...,Fantasy Impact: The status of Otton still isn'...,Category: Injury Updates
478,Jaylen Warren,"Mon, Sep 1st 12:07pm EDT",The Steelers signed RB Jaylen Warren to a two-...,Fantasy Impact: Warren lands a new deal a few ...,Category: Transactions
479,Darren Waller,"Mon, Sep 1st 12:04pm EDT",Darren Waller is on track to play in Sunday's ...,Fantasy Impact: Waller recently returned to pr...,Category: Injury Updates

In [15]:
formatted_news_df.to_csv('2025_news_formatted.csv',index=False)